### ISSUE TITLE
how do u do v:=value.Data() , value.Free() without losing "v" value?

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#36]
how do u do 
v:=value.Data()
value.Free() 

fmt.Printf("v = %v\n",v) // <- from here onwards, "v" is lost. how to prevent v from being lost?
this shld be mentioned as part of the caveats of this module coz it took me some time to realise this was the case and it was not obvious

````
        value, _ := db.Get(ro, k)
        //v := value.Data()
        b := make([]byte,value.Size())
        copy(b,value.Data())
        //defer value.Free()
        //fmt.Printf("gv = %v = %v = %v\n",v,value.Data(),b)
        value.Free()
        //fmt.Printf("gv1 = %v = %v = %v\n",v,value.Data(),b)
        return b
````

**Comment by linxGnu** [comment]
Yup, you should clone it:
```go
value, _ := db.Get(ro, k)

v := value.Data()
b := make([]byte, value.Size())
copy(b, v)

defer value.Free()
```

Now `b` is value you want

**Comment by hiqsociety** [comment]
defer is expensive and calling a new b:=make([]byte,value.Size()) seemed a bit redundant. any ways to minimize this overhead?

**Comment by linxGnu** [comment]
@hiqsociety you could remove `defer` if you want. I updated my comment above with the removal.

Since `db.Get` api hold underlying mem which allocated at cgo, go runtime has nothing to do with it and we have to manage ourself.

That's why clone is needed if you want to pass the value around (pass to other routine, use it later, etc). This pattern is quite common in cgo universe. You should be careful about moving c-value all around.
